### ISSUE TITLE
Limited search parameters

### ISSUE THREAD

**Issue by freelook** [arifulhb/amazon-pa-api50#1]
https://github.com/arifulhb/amazon-pa-api50/blob/d089c45e9d83ef6d5abcf392507eb0bd8e7db2fc/src/index.js#L152

With current implementation it is not possible to add custom search params from official documentation for paapi5 https://webservices.amazon.com/paapi5/documentation/search-items.html#ItemLookup-rp

Proposal: Merge by `Object.assign` second argument `params` with `getSearchItemsRequest`. Same approach can be applied for all methods: `getItemById`, `search`, `getVariations`, `getBrowseNodes`.

Best regards

**Comment by arifulhb** [comment]
Hi  @freelook , yes, still now a few more improvement opportunities is there. I hope I can push a new update ASAP, but can't confirm a solid date.
