### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Kinzi** [arifulhb/amazon-pa-api50#4]
I'm not 100% when this happens but it's probably on an empty or faulty response from the API:

```
SyntaxError: Unexpected token u in JSON at position 0
     at JSON.parse (<anonymous>)
     at /app/node_modules/amazon-pa-api50/src/index.js:181:38
    at /app/node_modules/amazon-pa-api50/sdk/src/ApiClient.js:504:9
```

It happens in those lines when `searchItemsResponse` is undefined:

https://github.com/arifulhb/amazon-pa-api50/blob/d089c45e9d83ef6d5abcf392507eb0bd8e7db2fc/src/index.js#L180-L181

So I guess it's either checking if `searchItemsResponse` actually is a JSON object or making sure `ProductAdvertisingAPIv1.SearchItemsResponse.constructFromObject(data)`does not return anything else.

**Comment by Kinzi** [comment]
Seems like this happens when you hit the request limit of the API.

**Comment by MaiKaY** [comment]
Hi @Kinzi,
I got the same error. Did you find a way to solve or at least try/catch it?

**Comment by Kinzi** [comment]
@MaiKaY Check out my fork. Not super elegant but at least it allows me to catch the error:

https://github.com/Kinzi/amazon-pa-api50

**Comment by arifulhb** [comment]
Hay, @Kinzi great to know you had time to fix the issue. Please send the PR and I'll just marge it.

**Comment by Kinzi** [comment]
@arifulhb @MaiKaY already did ;)
